<?php
/**
 * @package     Wright
 * @subpackage  Template File
 *
 * @copyright   Copyright (C) 2005 - 2016 Joomlashack. Meritage Assets.  All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>
<w:head />
</head>
<body>
<div id="toolbar">
	<div id="toolbar-inner">
		<div class="container_12 toolbar clearfix">
			<w:module type="grid" name="grid-top1" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>
<div id="header">
	<div id="header-inner">
		<div class="container_12 clearfix">
			<w:logo name="banner" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>
<?php if ($this->countModules('menu')) : ?>
<div id="menu">
	<div id="menu-inner">
		<div class="container_12 clearfix">
			<w:module name="menu" chrome="none" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>
<?php endif; ?>
<?php if ($this->countModules('grid-top2')) : ?>
<div id="stage">
	<div id="stage-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="grid-top2" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>
<?php endif; ?>
<?php if ($this->countModules('grid-top3')) : ?>
<div class="elements">
	<div class="elements-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="grid-top3" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<div class="clear"></div>
<?php endif; ?>
<div id="container">
	<div id="container-inner">
		<div class="container_12 clearfix">
			<section id="main">
				<?php if ($this->countModules('breadcrumb')) : ?>
				<div id="pathway">
					<div id="pathway-inner">
						<w:module type="single" name="breadcrumb" chrome="none" />
						<div class="clear"></div>
					</div>
				</div>
				<div class="clear"></div>
				<?php endif; ?>
				<w:content />
			</section>
			<aside id="sidebar1">
				<w:module name="sidebar1" chrome="xhtml" />
			</aside>
			<aside id="sidebar2">
				<w:module name="sidebar2" chrome="xhtml" />
			</aside>
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php if ($this->countModules('grid-bottom1')) : ?>
<div id="bottom">
	<div id="bottom-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="grid-bottom1" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>
<div id="footer">
	<div id="footer-inner">
		<div class="container_12">
			<div id="copy" class="grid_6">
				<w:module type="single" name="footer" chrome="none" />
				<w:footer />
			</div>
			<?php if ($this->countModules('bottommenu')) : ?>
			<div id="link" class="grid_6">
				<w:module type="single" name="bottommenu" chrome="none" />
			</div>
			<?php endif; ?>
			<div class="clear"></div>
		</div>
	</div>
</div>
</body>
</html>
