<?php
/**
 * @copyright	Copyright (C) 2005 - 2010 Joomlashack / Joomlapraise / Meritage Assets
 * @author		Jeremy Wilken - Joomlashack
 * @package		Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>
<w:head />
</head>
<body>

<div id="header">
	<div id="header-inner">
		<div class="container_12">
			<w:logo name="banner" />	
			<div class="clear"></div>
		</div>
	</div>
</div>

<?php if ($this->countModules('menu')) : ?>
<div id="mainmenu">
	<div id="mainmenu-inner">
		<w:nav wrapclass="container_12 clearfix" />
	</div>
</div>
<?php endif; ?>

<?php if ($this->countModules('stage')) : ?>
<div id="stage">
	<div id="stage-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="stage" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>


<div id="container">
	<div id="container-inner">
		<div id="container-wrapper" class="container_12">
			<?php if ($this->countModules('user1')) : ?>
			<div class="elements">
				<w:module type="grid" name="user1" chrome="wrightflexgrid" />
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
			<?php endif; ?>
			<?php if ($this->countModules('user2')) : ?>
			<div class="elements">
				<w:module type="grid" name="user2" chrome="wrightflexgrid" />
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
			<?php endif; ?>
			<section id="main">
				<w:content />
			</section>
			<aside id="sidebar1">
				<w:module name="sidebar1" chrome="xhtml" />
			</aside>
			<aside id="sidebar2">
				<w:module name="sidebar2" chrome="xhtml" />
			</aside>
			<div class="clear"></div>
		</div>
	</div>
</div>

<?php if ($this->countModules('user7')) : ?>
<div id="bottom">
	<div id="bottom-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="user7" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>

<?php if (($this->countModules('user8')) || ($this->countModules('footer'))) : ?>
<div id="footer">
	<div id="footer-inner">
		<div class="container_12">
			<?php if ($this->countModules('user8')) : ?>
			<div id="link" class="grid_8">
				<w:module type="single" name="user8" chrome="none" />
			</div>
			<?php endif; ?>
			<?php if ($this->countModules('footer')) : ?>
			<div id="copy" class="grid_4">
				<w:footer />
			</div>
			<?php endif; ?>
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>
<?php echo $this->params->get("footerscript",""); ?>
</body>
</html>