<?php
/**
 * @copyright	Copyright (C) 2005 - 2010 Joomlashack / Joomlapraise / Meritage Assets
 * @author		Jeremy Wilken - Joomlashack
 * @package		Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */

// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>
<w:head />
</head>
<body>
<div id="header">
	<div id="header-inner">
		<div class="container_12">
			<w:logo name="topmenu" />	
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php if ($this->countModules('grid-top1')) : ?>
<div id="stage">
	<div id="stage-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="grid-top1" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>
<div id="container">
	<div id="container-inner">
		<div class="container_12">
			<?php if ($this->countModules('grid-top2')) : ?>
			<div class="elements">
				<w:module type="grid" name="grid-top2" chrome="wrightflexgrid" />
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
			<?php endif; ?>
			<?php if ($this->countModules('grid-top3')) : ?>
			<div class="elements">
				<w:module type="grid" name="grid-top3" chrome="wrightflexgrid" />
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
			<?php endif; ?>
			<?php if ($this->countModules('breadcrumb')) : ?>
			<div id="pathway">
				<div class="container_12 clearfix">
					<w:module type="grid" name="breadcrumb" chrome="wrightflexgrid" />
					<div class="clear"></div>
				</div>
			</div>
			<div class="clear"></div>
			<?php endif; ?>
			<section id="main">
				<jdoc:include type="message" />
				<w:content />
			</section>
			<aside id="sidebar1">
				<w:module name="sidebar1" chrome="xhtml" />
			</aside>
			<aside id="sidebar2">
				<w:module name="sidebar2" chrome="xhtml" />
			</aside>
			<div class="clear"></div>
		</div>
	</div>
</div>

<?php if ($this->countModules('grid-bottom1')) : ?>
<div id="bottom">
	<div id="bottom-inner">
		<div class="container_12 clearfix">
			<w:module type="grid" name="grid-bottom1" chrome="wrightflexgrid" />
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>

<?php if (($this->countModules('bottommenu')) || ($this->countModules('footer'))) : ?>
<div id="footer">
	<div id="footer-inner">
		<div class="container_12">
			<?php if ($this->countModules('bottommenu')) : ?>
			<div id="link" class="grid_6">
				<w:module type="single" name="bottommenu" chrome="none" />
			</div>
			<?php endif; ?>
			<?php if ($this->countModules('footer')) : ?>
			<div id="copy" class="grid_6">
				<w:module type="single" name="footer" chrome="none" />
				<w:footer />
			</div>
			<?php endif; ?>
			<div class="clear"></div>
		</div>
	</div>
</div>
<?php endif; ?>
<?php echo $this->params->get("footerscript",""); ?>
</body>
</html>